apiVersion: apps/v1
kind: Deployment
metadata:
  name: greenledger-app
  namespace: default
  labels:
    app: greenledger
    version: v1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: greenledger
  template:
    metadata:
      labels:
        app: greenledger
        version: v1.0.0
    spec:
      containers:
      - name: greenledger-frontend
        image: greenledger:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            configMapKeyRef:
              name: greenledger-config
              key: api-url
        - name: NEXT_PUBLIC_CHAIN_ID
          valueFrom:
            configMapKeyRef:
              name: greenledger-config
              key: chain-id
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      - name: greenledger-backend
        image: greenledger-backend:latest
        ports:
        - containerPort: 5000
          name: api
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "5000"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: greenledger-secrets
              key: database-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: greenledger-secrets
              key: jwt-secret
        - name: INFURA_API_KEY
          valueFrom:
            secretKeyRef:
              name: greenledger-secrets
              key: infura-api-key
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: docker-registry-secret
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: greenledger-service
  labels:
    app: greenledger
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: api
  selector:
    app: greenledger
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: greenledger-config
data:
  api-url: "https://api.greenledger.io"
  chain-id: "1"
  ipfs-gateway: "https://gateway.pinata.cloud/ipfs/"
  network-name: "mainnet"
---
apiVersion: v1
kind: Secret
metadata:
  name: greenledger-secrets
type: Opaque
stringData:
  database-url: "postgresql://user:password@postgres:5432/greenledger"
  jwt-secret: "your-super-secret-jwt-key-here"
  infura-api-key: "your-infura-api-key-here"
  private-key: "your-ethereum-private-key-here"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: greenledger-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - greenledger.io
    - api.greenledger.io
    secretName: greenledger-tls
  rules:
  - host: greenledger.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: greenledger-service
            port:
              number: 80
  - host: api.greenledger.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: greenledger-service
            port:
              number: 5000
